---
services:
  python-client:
    image: python:3-bookworm
    container_name: python-client
    hostname: python-client
    user: "${UID:-1000}:${GID:-1000}"
    restart: "no"
    command: python /app/src/bloomFilter/tcpClient.py bloom-filter 12345
    volumes:
      - ./:/app/
    depends_on:
      bloom-filter:
        condition: service_healthy
    networks:
      - bmail


networks:
  bmail:
    name: bmail